services:
  db:
    image: postgres:16
    container_name: erp_postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: erp_transporte
    ports:
      - "5432:5432"
    volumes:
      - erp_pg:/var/lib/postgresql/data

volumes:
  erp_pg:
